version: '3.7'

services:
  pihole:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    env_file:
      - .env
    environment:
      TZ: 'Europe/Zurich'
      DNSSEC: "true"
      DNS_BOGUS_PRIV: "true"
      #ServerIP: "${ServerIP}" in .env file
      #ServerIPv6: "${ServerIPv6}" in .env file
      TEMPERATUREUNIT: "c"
      WEBUIBOXEDLAYOUT: "boxed"
    #volumes:
    #  - ${host_etc_pihole}:/etc/pihole/ #in .env file
    #  - ${host_etc_dnsmasq}:/etc/dnsmasq.d/ #in .env file
    cap_add:
      - NET_ADMIN
    restart: always
    networks: 
      - home-network

networks:
  home-network:
    name: home-network
    driver: bridge