version: '3.7'

services:
  pihole:
    container_name: pihole
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Zurich'
      DNSSEC: "true"
      DNS_BOGUS_PRIV: "true"
      ServerIP: 192.168.1.102
      WEBPASSWORD: test1234
      TEMPERATUREUNIT: "c"
      WEBUIBOXEDLAYOUT: "boxed"
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: always
    networks: 
      - home-network

networks:
  home-network:
    name: home-network
    driver: bridge